# Generated by Django 5.0.6 on 2024-06-21 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dailyTasks',
            fields=[
                ('dailyTaskID', models.AutoField(primary_key=True, serialize=False)),
                ('dailyTask_name', models.TextField()),
                ('dailyStartTime', models.TimeField()),
                ('dailyEndTime', models.TimeField()),
                ('dailyTaskStatus', models.BooleanField(default=False)),
            ],
        ),
    ]
