# Generated by Django 5.0.6 on 2024-05-31 03:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dailyTasks',
            fields=[
                ('dailyTaskID', models.AutoField(primary_key=True, serialize=False)),
                ('dailyTask_name', models.TextField()),
                ('dailyTimeHr', models.IntegerField(default=8, validators=[django.core.validators.MaxValueValidator(23), django.core.validators.MinValueValidator(0)])),
                ('dailyTimeMin', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(59), django.core.validators.MinValueValidator(0)])),
                ('dailyTaskStatus', models.BooleanField(default=False)),
            ],
        ),
    ]
